# Generated by Django 4.2.7 on 2023-11-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatgroup'),
        ),
    ]
