# Generated by Django 4.2.7 on 2023-11-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatgroup_messages_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_group',
        ),
    ]
